import { Request, Response } from 'express';
import { CreateRadiologyReportDto, CreateRadiologyRequestDto, CreateRadiologyTestDto, UpdateRadiologyRequestStatusDto, UpdateRadiologyTestDto } from './radiology.dto';
import { RadiologyService } from './radiology.service';

export class RadiologyController {
  private service = new RadiologyService();
  getTests = async (req: Request, res: Response) => { try { res.status(200).json({ data: await this.service.getAllTests(String(req.query.includeInactive || 'false') === 'true', req.user?.role) }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch radiology tests' }); } };
  createTest = async (req: Request, res: Response) => { try { res.status(201).json({ message: 'Radiology test created', data: await this.service.createTest(CreateRadiologyTestDto.parse(req.body)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to create radiology test' }); } };
  updateTest = async (req: Request, res: Response) => { try { res.status(200).json({ message: 'Radiology test updated', data: await this.service.updateTest(String(req.params.id), UpdateRadiologyTestDto.parse(req.body)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to update radiology test' }); } };
  deactivateTest = async (req: Request, res: Response) => { try { res.status(200).json({ message: 'Radiology test deactivated', data: await this.service.deactivateTest(String(req.params.id)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to deactivate radiology test' }); } };
  getRequests = async (req: Request, res: Response) => { try { res.status(200).json({ data: await this.service.getAllRequests({ status: req.query.status ? String(req.query.status) : undefined, patientId: req.query.patientId ? String(req.query.patientId) : undefined, doctorId: req.query.doctorId ? String(req.query.doctorId) : undefined }) }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch radiology requests' }); } };
  getRequestById = async (req: Request, res: Response) => { try { const data = await this.service.getRequestById(String(req.params.id)); if (!data) { res.status(404).json({ message: 'Radiology request not found' }); return; } res.status(200).json({ data }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch radiology request' }); } };
  createRequest = async (req: Request, res: Response) => { try { res.status(201).json({ message: 'Radiology request created', data: await this.service.createRequest(CreateRadiologyRequestDto.parse(req.body)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to create radiology request' }); } };
  updateRequestStatus = async (req: Request, res: Response) => { try { res.status(200).json({ message: 'Radiology request status updated', data: await this.service.updateRequestStatus(String(req.params.id), UpdateRadiologyRequestStatusDto.parse(req.body)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to update status' }); } };
  createReport = async (req: Request, res: Response) => { try { res.status(201).json({ message: 'Radiology report uploaded', data: await this.service.createReport(CreateRadiologyReportDto.parse({ ...req.body, radiologyRequestId: req.params.id || req.body.radiologyRequestId })) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to create radiology report' }); } };
  getReport = async (req: Request, res: Response) => { try { const data = await this.service.getReportById(String(req.params.id)); if (!data) { res.status(404).json({ message: 'Radiology report not found' }); return; } res.status(200).json({ data }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch radiology report' }); } };
  getPatientRadiologyData = async (req: Request, res: Response) => { try { res.status(200).json({ data: await this.service.getRequestsByPatientId(String(req.params.patientId)) }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch patient radiology data' }); } };
}
