import { Request, Response } from 'express';
import { CreateLabReportDto, CreateLabRequestDto, CreateLabTestDto, UpdateLabRequestStatusDto, UpdateLabTestDto } from './lab.dto';
import { LabService } from './lab.service';

export class LabController {
  private service = new LabService();
  getTests = async (req: Request, res: Response) => { try { res.status(200).json({ data: await this.service.getAllTests(String(req.query.includeInactive || 'false') === 'true') }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch lab tests' }); } };
  createTest = async (req: Request, res: Response) => { try { res.status(201).json({ message: 'Lab test created', data: await this.service.createTest(CreateLabTestDto.parse(req.body)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to create lab test' }); } };
  updateTest = async (req: Request, res: Response) => { try { res.status(200).json({ message: 'Lab test updated', data: await this.service.updateTest(String(req.params.id), UpdateLabTestDto.parse(req.body)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to update lab test' }); } };
  deactivateTest = async (req: Request, res: Response) => { try { res.status(200).json({ message: 'Lab test deactivated', data: await this.service.deactivateTest(String(req.params.id)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to deactivate lab test' }); } };
  getRequests = async (req: Request, res: Response) => { try { res.status(200).json({ data: await this.service.getAllRequests({ status: req.query.status ? String(req.query.status) : undefined, patientId: req.query.patientId ? String(req.query.patientId) : undefined, doctorId: req.query.doctorId ? String(req.query.doctorId) : undefined }) }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch lab requests' }); } };
  getRequestById = async (req: Request, res: Response) => { try { const data = await this.service.getRequestById(String(req.params.id)); if (!data) { res.status(404).json({ message: 'Lab request not found' }); return; } res.status(200).json({ data }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch lab request' }); } };
  createRequest = async (req: Request, res: Response) => { try { res.status(201).json({ message: 'Lab request created', data: await this.service.createRequest(CreateLabRequestDto.parse(req.body)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to create lab request' }); } };
  updateRequestStatus = async (req: Request, res: Response) => { try { res.status(200).json({ message: 'Lab request status updated', data: await this.service.updateRequestStatus(String(req.params.id), UpdateLabRequestStatusDto.parse(req.body)) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to update status' }); } };
  createReport = async (req: Request, res: Response) => { try { res.status(201).json({ message: 'Lab report uploaded', data: await this.service.createReport(CreateLabReportDto.parse({ ...req.body, labRequestId: req.params.id || req.body.labRequestId })) }); } catch (err: any) { res.status(400).json({ message: err.message || 'Failed to create lab report' }); } };
  getReport = async (req: Request, res: Response) => { try { const data = await this.service.getReportById(String(req.params.id)); if (!data) { res.status(404).json({ message: 'Lab report not found' }); return; } res.status(200).json({ data }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch lab report' }); } };
  getPatientLabData = async (req: Request, res: Response) => { try { res.status(200).json({ data: await this.service.getRequestsByPatientId(String(req.params.patientId)) }); } catch (err: any) { res.status(500).json({ message: err.message || 'Failed to fetch patient lab data' }); } };
}
